#!/usr/bin/env sh

# Terminate already running bar instances
killall -q dunst

# Wait until the processes have been shut down
while pgrep -x dunst > /dev/null; do sleep 1; done

# Launch bar1 and bar2

dunst & 

echo "Dunst launched..."
notify-send "Dunst launched"
