#!/bin/bash

OPTIONS="Laptop\nHDMI\nVGA\nDual (Laptop main + HDMI)\nDual (HDMI main + laptop)\nDual (VGA main + laptop)\nDual (Laptop main + VGA)\nManual"

SELECTED=$(echo -e $OPTIONS | rofi -dmenu -i -p "xrandr")

case "$SELECTED" in
    Laptop) xrandr --output eDP-1 --auto --output HDMI-2 --off --output DP-1 --off;;
    HDMI) xrandr --output HDMI-2 --auto --output eDP-1 --off --output DP-1 --off;;
    VGA) xrandr --output DP-1 --auto --output HDMI-2 --off --output eDP-1 --off;;
    "Dual (Laptop main + HDMI)") xrandr --output eDP-1 --primary --auto --output HDMI-2 --auto --right-of eDP-1 --output "DP-1" --off;;
    "Dual (Laptop main + VGA)") xrandr --output eDP-1 --primary --auto --output DP-1 --auto --right-of eDP-1 --output HDMI-2 --off;;
    "Dual (HDMI main + laptop)") xrandr --output eDP-1 --auto --output DP-1 --off --output HDMI-2 --auto --primary --left-of eDP-1;;
    "Dual (VGA main + laptop)") xrandr --output eDP-1 --auto --output DP-1 --auto --primary --left-of eDP-1;;
    Manual) arandr;;
esac

