#!/bin/bash

OPTIONS="Laptop\nHDMI\nVGA\nDual (Laptop main + HDMI)\nDual (HDMI main + laptop)\nDual (VGA main + laptop)\nDual (Laptop main + VGA)\nManual"

SELECTED=$(echo -e $OPTIONS | rofi -dmenu -i -p "xrandr")

case "$SELECTED" in
    Laptop) xrandr --output eDP1 --auto --output HDMI2 --off --output DP1 --off;;
    HDMI) xrandr --output HDMI2 --auto --output eDP1 --off --output DP1 --off;;
    VGA) xrandr --output DP1 --auto --output HDMI2 --off --output eDP1 --off;;
    "Dual (Laptop main + HDMI)") xrandr --output eDP1 --primary --auto --output HDMI2 --auto --right-of eDP1 --output "DP1" --off;;
    "Dual (Laptop main + VGA)") xrandr --output eDP1 --primary --auto --output DP1 --auto --right-of eDP1 --output HDMI2 --off;;
    "Dual (HDMI main + laptop)") xrandr --output eDP1 --auto --output DP1 --off --output HDMI2 --auto --primary --left-of eDP1;;
    "Dual (VGA main + laptop)") xrandr --output eDP1 --auto --output DP1 --auto --primary --left-of eDP1;;
    Manual) arandr;;
esac

